Name: Cityscapes
box_threshold: 0.18
text_threshold: 0.15
iou_threshold: 0.8
example_size: 0
input_dir: "../../datasets/segmentation/Cityscapes/val_imgs"
gt_dir: "../../datasets/segmentation/Cityscapes/val_masks"
label_list: "background, road, sidewalk, building, wall, fence, pole, traffic-light, traffic-sign, tree, terrain, sky, person, rider, car, truck, bus, train, motorcycle, bicycle"
mask_ids: [0, 7, 8, 11, 12, 13, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 31, 32, 33]
llm_model: "Meta-Llama-3-8B-Instruct" # supported models: ["gpt-4o", "gpt-4-turbo", "gpt-4o-mini", "gpt-4-0125-preview", "gpt-4-1106-preview", "gpt-3.5-turbo-0125", "Meta-Llama-3-8B-Instruct"], the reported results in the paper are based on "gpt-4-0125-preview"
api_key: "Insert your API key here if you want to use OpenAI API"